### ISSUE TITLE
Website Support no menu Odoo 11, also Analytics, Billing and Gamification fail to install

### ISSUE THREAD

**Issue by hindsa-nabeel** [SythilTech/Odoo#29]
Hi,
The latest incarnation of Website Support installs without errors on Odoo 11, but does not seem to show in any of the menus. Website_Support 1.2.14 (this commit: ddfaa97) installs and shows in the top menu as Customer Support, but the other 3 Website -Support Analytics, Billing and Gamification, fail to install henceforth.

The only way to make Website -Support Analytics, Billing and Gamification install is to bring back Website_Support version 1.2.13..

Nabeel.

**Comment by SythilTech** [comment]
Hi,

I have released version 1.0.6 of website_support_analytic_timesheets to address the compatibility issue with 1.2.14, it should also remain compatible with older versions of the core module too.

 I was not able to reproduce any issue with installing website_support_billing or website_support_gamification though.

Regards
Steven

**Comment by hindsa-nabeel** [comment]
Your prompt response and fixing the installation issue is greatly appreciated. The failure (in my case) of the subsequent modules to install is probably due to the second module failed installation and its prerequisites.

I downloaded the latest commitment 05f6299 and installed the 4 Website-Support modules on a fresh Odoo 11 / Centos 7.5. All 4 modules of Website Support installed without a hitch. 

Initially the menu had Apps and Settings, 
- Installing Website-Support added "Discuss" and "Website" to the menu
- Installing Analytics added "Project", "Timesheets" and "Employees" to the menu
- Installing Billing added "Invoicing"
- Finally installing Gamification did not add anything to the menu

However, the installation process did not add "Customer Support", like in 1.2.14, to the main menu and I cannot find any reference indicating the utilization of the added modules. I would appreciate feedback on access menus to configure the Website-Support module.

By the way, if you install 1.2.14 first, it adds Calendar, Contacts, CRM and Customer Support to the top menu, and if you then upgrade to 1.3.1, Customer Support stays in the top menu, but you loose all the side menus of Customer Support.

Best regards.
Nabeel.

**Comment by SythilTech** [comment]
Yes the last few commits have introduced major changes in the design so I'll explain things a bit.

v1.2.14 revamped the fake ticket number system allowing for greater control over how it is displayed, it also moved the support ticket menus from being under CRM to it's own top level menu "Customer Support"

This resulted in some permission issues, in previous versions anyone that was in the Sales Manager groups could access crm configuration menu including the support ticket configuration menus.

v1.3.0 resolves this by revamping the entire design of permissions, instead of relying on Sales Manager it instead introduced new groups "Support Staff" and "Support Manager", staff is for people answering tickets while manager is for people that need to configure the support ticket settings.

This changes was to separate the module from being a simple CRM extension that it's own stand alone app.

v1.3.1 then removes dependencies on the crm module as the module only ever piggy backed on it's menu structure and permission system so it was no longer needed.

As the result of this major overhaul people upgrading from older version will need to assign there users to the new "Support Staff" and "Support Manager" to see the new "Customer Support" top level menu this in place of the old "Sales / All documents" and "Sales Manager" that the old CRM centric design used.

And to sum up the design of each module
- Website-Support is mostly about the Customer Support top level menu and the help documentation on the website
- Analytics adds times sheets to the tickets so you can track time spent on the ticket, it's linked with time spent on tasks too
- Billing adds an action to the more menu of customers that lets you generate an invoice for customers based on all tickets and tasks completed within a specified time frame (e.g. total hours spent answers ticket throughout the month)
- Gamification does add any menus but it adds a lot of new challenges and badges that are automatically awarded to your support staff based on various performance milestones.

Hopefully that clears up some of the recent major changes.

**Comment by hindsa-nabeel** [comment]
Thanks Steven,
I have reinstalled Centos 7.5 and Odoo 11 then the latest (1.3.1) Website Support module (only) as I need to understand the logic and learn the layout of menus and where to find things.

After creating the Support personnel and Support Manager and logging out as Administrator and re-logging in as Support manager, the Customer Support title appears in the top menu.

I must say that I and many others are grateful for your excellent work..

Best regards,
Nabeel.
